
#define TAM_NOME 4
#define MAX 32
#define TOPX 160
#define TOPY 68
#define BOTX 479
#define BOTY 131
#define HY BOTY-TOPY
#define QTD_H 8
#define XINIC 8
#define YINIC 4
#define DESLOC_V 16
#define DESLOC_H 40
#define X 2
#define Y 4

#define POS_XT_RET 200
#define POS_YT_RET 100
#define POS_XB_RET 510
#define POS_YB_RET 136

#define QTD_OPCOES_ARQ 3
#define POS_ARQ_X 240
#define POS_ARQ_Y  30

#define FALSE 0
#define TRUE  0xFF
#define TAM_ICONE 1434

#define MOUSE   0x33
#define CURSOR  0x10
#define DISK    0x13
#define PRINTER 0x17

#define INI_OP_Y 0
#define INI_OP_X 0
#define FIM_OP_Y 19
#define FIM_OP_X 639
#define NR_OP 3

#define TOPX 160
#define TOPY 68

